### ISSUE TITLE
Running minzinc with timeout will not show intermediate solutions

### ISSUE THREAD

**Issue by telebog** [MiniZinc/MiniZincIDE#106]
![image](https://user-images.githubusercontent.com/7736319/84694355-5b73a380-af49-11ea-8370-cbe7ffccdd49.png)

There are a few intermediate solutions that are displayed when I use -a option. Without this option I get =====UNKNOWN=====

**Comment by cyderize** [comment]
I think this is expected behaviour - when you don't specify `-a` then when the timeout happens, the solver still hasn't output anything (because it's being told to only output something that's optimal), so you get the unknown status.

Gecode has a feature where when it times out, it outputs the best solution so far, but chuffed does not do this, so if you want to find the best solution after a certain amount of time, you'll have to specify `-a`.
