### ISSUE TITLE
Output console does not print trace text

### ISSUE THREAD

**Issue by GustavBjordal** [MiniZinc/MiniZincIDE#114]
When running the MiniZinc IDE, trace is not printed for me unless the model is unsat.
```
var 1..10: x;
constraint trace("foo", true);
% constraint trace("bar", false); %% Tracing works when the model is unsatisfiable.
```
gives
```
Running foo.mzn
x = 1;
----------
Finished in 65msec
```
but uncommenting the second constraint gives
```
Running foo.mzn
foobar
  WARNING: model inconsistency detected
=====UNSATISFIABLE=====
Finished in 46msec
```

When I run the model (without the second constraint) via the command-line I get:
```
>./minizinc foo.mzn 
foox = 1;
----------
```

**Comment by cyderize** [comment]
I think this should be fixed in the develop branch now - I've tried to more accurately emulate console behaviour.

In general, it's probably safer to always end a trace string with `\n` if possible, since that's essentially what triggers printing to the console. I've now changed it so that a new line in stdout will trigger the printing of anything left in stderr, which is more similar to what happens on the command line.
