### ISSUE TITLE
Overlapping text in options selectors

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/MiniZincIDE#124]
Using MiniZincIDE 2.5.2 on macOS Catalina 10.15.6 in dark mode, using a selector for an option results in overlapping text as in the below screenshot. The overlapping text resolves itself when clicking somewhere else so that the selector loses focus. 

<img width="634" alt="Screenshot 2020-11-17 at 09 29 17" src="https://user-images.githubusercontent.com/245350/99370355-ddcc0f00-28bd-11eb-8049-8cadc0c90fca.png">

**Comment by cyderize** [comment]
It seems like this is probably an issue in Qt (or their design for how the table widget works). I tried making a new Qt project with a table widget and an editable boolean value, and the same thing happened.

I think the background of the combo box is semi-transparent in dark mode, and so you can see the text underneath. It is possible to customize the editor widgets to add them to a widget with an opaque background (but that annoyingly breaks some other things and messes up the sizes). Using a stylesheet to force the background to be opaque seems to make Qt use its own custom widget instead of the native combo box, which looks horrible too.

I'll see if I can find some other quick workaround, but at least it's only a relatively minor inconvenience.

**Comment by zayenz** [comment]
I agree that it is a minor inconveniance, and clearly not worth making the widget worse in other ways.

One potential work-around could be to remove focus from the widget after choosing a value, but that would perhaps be hard to do and also be an inconvenience for keyboard navigation.
