### ISSUE TITLE
When "Output solving statistics" is set, Gecode Gist runs Gecode instead

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/MiniZincIDE#125]
Using MiniZincIDE 2.5.2 on macOS Catalina, setting the "Output solving statistics" flag for Gecode Gist makes the solver run normal non-graphical Gecode instead.

**Comment by cyderize** [comment]
I think this is due to a quirk in Gecode, as emitting statistics and running in Gist mode are mutually exclusive (as they are both Gecode modes).

We should probably just disable the statistics option for Gecode Gist in the IDE (just use normal Gecode if you want stats), or perhaps see if it's possible to make Gecode support statistics output in Gist mode.

**Comment by zayenz** [comment]
Good point. Yes, we should probably fix the Gecode back-end to make `-mode gist` overrride `-s` (I'll add a related bug for that). I think that making Gist output statistics might be hard to do, but I haven't looked into it..

I agree that disabling the option in the GUI is probably a good idea.

**Comment by cyderize** [comment]
The statistics option for Gist has now been disabled in the IDE, so I'm going to close this issue for now since you've already added the Gecode issue.
