### ISSUE TITLE
IDE doesn't ask for data file

### ISSUE THREAD

**Issue by pjbgtnj** [MiniZinc/MiniZincIDE#136]
Below is a simple example that illustrates the issue.  I believe the IDE should recognize that a parameter/data file is needed and ask the user to select one.  Instead you get the error "MiniZinc: type error: undefined identifier `EVE'".

patrol.mzn
```
int: num;
enum SHIFT;

array[1..num] of var SHIFT: roster;

var int: onEve;
constraint onEve = sum(s in 1..num) (roster[s]=EVE);

solve maximize onEve;
```

patrol.dzn
```
SHIFT = {EVE,NIGHT,OFF};
num = 7;
```

**Comment by Dekker1** [comment]
This seems to be an issues with the enum. When the definition of the enum is defined in the model, then the IDE has the correct behaviour.

**Comment by cyderize** [comment]
This is due to `EVE` being undefined in the model. Since the model itself does not typecheck, the IDE cannot determine what parameters to ask for. Maybe MiniZinc's model interface check needs to be able to deal with undefined identifiers since they may be defined in data later on.

Although I think most of the time if you are hardcoding use of particular enum values in your model, then the definition of the enum should probably be in the model and not in the data.

**Comment by guidotack** [comment]
That's right, you can't use an enum value in a model if that value is only defined in a data file. The correct way to do this is to define a parameter
`SHIFT: eveningShift;`
in your model, and use that instead of `EVE`. Your data file then needs to define
`eveningShift = EVE;`

Cheers,
Guido
