### ISSUE TITLE
Snap install gives segmentation fault upon booting

### ISSUE THREAD

**Issue by Jensonah** [MiniZinc/MiniZincIDE#140]
Hi!

Problem: MiniZinc doesn't launch from terminal and Ubuntu launcher.

Details:
I'm on Ubuntu 20.04
I've installed minizinc with snap:
`snap install minizinc --classic`
Running minizinc with:
`minizinc.ide`
Gives:
```
(MiniZincIDE:4964): Gtk-WARNING **: 20:43:05.417: Theme parsing error: gtk.css:1521:23: 'font-feature-settings' is not a valid property name

(MiniZincIDE:4964): Gtk-WARNING **: 20:43:05.420: Theme parsing error: gtk.css:3460:25: 'font-feature-settings' is not a valid property name

(MiniZincIDE:4964): Gtk-WARNING **: 20:43:05.421: Theme parsing error: gtk.css:3922:23: 'font-feature-settings' is not a valid property name
Segmentation fault (core dumped)
```

For now I can use the tar.gz but I'd like to use snap for the OS integration.

Thanks in advance,

Jens

**Comment by cyderize** [comment]
There was a problem with packaging of the mesa drivers which was causing them to crash (depending on what graphics card you have - it seems to affect Intel graphics). This should now be fixed (you might have to do `sudo snap refresh --classic minizinc` if your `snapd` hasn't auto updated.

I'm hoping that was the cause of the crash - otherwise further investigation will be required.

**Comment by tassosblackg** [comment]
It seems that `sudo snap refresh --classic minizinc` worked.Thanks!

**Comment by Jensonah** [comment]
I installed it again and it now works!
