### ISSUE TITLE
problem to start MiniZinc 2.6

### ISSUE THREAD

**Issue by DvonHolten** [MiniZinc/MiniZincIDE#155]
after installation of the newest version i cannot start the IDE.
i get a prompt:
'procedure entrypoint 'CreateDXGIFactory2' could not be located in 'dxgi.dll" 

there is no such dll in the minizinc-installation folder.
what can i do?
the previous version worked fine.

**Comment by cyderize** [comment]
@DvonHolten, what version of Windows are you using? I just noticed that Qt 6 doesn't officially support Windows 7/8/8.1 anymore (and mainstream support for those version already ended).

Otherwise we'll have to investigate if there's some dependency that's not being included correctly anymore.

**Comment by DvonHolten** [comment]
it's win7. you may be right with the Qt6-version. 
btw, i see, that the size of the version 2.6 download is *much* smaller (27 MB) compared to version 2.5.5 (61MB). 
is it just the  IDE or does it include updated solvers?

**Comment by cyderize** [comment]
The IDE download is smaller because we no longer use the Qt WebEngine (it was previously used for visualisations, but that has now been re-implemented without the need for the WebEngine).

The bundle does include updated solvers, although my understanding is that there have only been minor changes to the solvers since the last release.

**Comment by cyderize** [comment]
Hi, I'm going to close this issue because it seems to be specific to a version of Windows which is no longer supported. Unfortunately we don't have the resources to test and maintain compatibility with Windows 7/8.

If you still experience this problem in Windows 10/11, feel free to reopen this.
