### ISSUE TITLE
Minizinc command line vs. minizinc/IDE discrepancy

### ISSUE THREAD

**Issue by krzku** [MiniZinc/MiniZincIDE#159]
There is a discrepancy between handling of solver generated statistics in command line (minizinc command) and IDE. For example, printing values with thousand delimiters (for example, 11,222,333 or 11 222 333) works fine when run from the command line, it generates an error when run in IDE. Is it a different program that parses lines starting with '%%%mzn-stat:' in IDE? Why it cannot have the same behaviour?

**Comment by cyderize** [comment]
Statistics are supposed to be values of a MiniZinc type (https://www.minizinc.org/doc-2.6.1/en/fzn-spec.html#statistics-output)
> The `<name>` describes the kind of statistics gathered, and the `<value>` can be any value of a MiniZinc type.

This was previously not enforced (it has been in the spec for a long time), but the IDE now uses the `--json-stream` option where MiniZinc parses the statistics to convert them into JSON for the IDE to read.

**Comment by krzku** [comment]
Thanks for the explanation. It is logical, of course, but you may consider representation of big numbers in the format accepted by Java, where thousand delimiter is '_', that is big numbers can be written as 11_222_333. It improves readability ver much. 

BTW, an additional statistics field might be useful. I mean "number of visited nodes per second". It can be computed from other values but explicit reporting might be nice.

**Comment by Dekker1** [comment]
It is possible for solvers to report other statistics than the ones listed in the documentation. The listed statistics are merely a suggestion to solver implementers as statistics that would be interesting for most users.

Although I understand the interest in aggregated statistics, I'm not sure how common their usage is and if they warrant direct support from the MiniZinc infrastructure. Especially, since the statistics are already hard to compare between different solvers, and much thought should go into if a comparison is fair or not. For larger benchmarks aggregating statistics according to personal preference is trivial using a scripting language (for example using MiniZinc Python), which is likely to be used instead of the IDE to begin with.

I agree that having some visual way to seperate big numbers would be nice. We might introduce this feature in future versions of the MiniZinc language.
