### ISSUE TITLE
Minizinc IDE does not open anymore

### ISSUE THREAD

**Issue by peykaf** [MiniZinc/MiniZincIDE#166]
Hello,

I am using Minizinc IDE (the latest version) on Windows 10. I have been using it for a time and everything was fine. All of a sudden, when I wanted to open Minizinc IDE, it shows that it is open in the taskbar, but the IDE windows does not appear! when I hover the mouse over the icon in the taskbar, it shows a white rectangle! I waited for an hour and no change, restarted my PC, uninstalled Minizinc software, and re-installed it again, but none of these have helped! Any suggestions?

**Comment by a1880** [comment]
Their might be a problem with your search path. Or some dynamic link libararies (DLL) might be missing or hidden.
You could try a dependency checker like [https://github.com/lucasg/Dependencies](https://github.com/lucasg/Dependencies) to find and solve the problem.

**Comment by cyderize** [comment]
I believe we have now fixed this issue in 2.7.0 - previously it was possible for the main window to spawn somewhere off-screen (especially in multi monitor setups after unplugging the screen where the IDE was located), making it appear like the window hasn't opened, even though the IDE still appears in the taskbar.

I'm going to close this issue because I think that this is now fixed. Feel free to reopen this if the issue still persists.
