### ISSUE TITLE
No libEGL library in 2.7.2 AppImage

### ISSUE THREAD

**Issue by ArtyomKaltovich** [MiniZinc/MiniZincIDE#175]
Hello. I am sorry it this is not correct place for this issue, or this isn't issue at all.

Description:
I use minizinc appimage distribution in ci for one of my project, and it failed with error:

`UNEXPECTED EXCEPTION: MiniZincError('/tmp/.mount_miniziMxUR6D/usr/bin/fzn-gecode: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory')`

E.g. https://github.com/ArtyomKaltovich/zython/actions/runs/4632415355/jobs/8196445948#step:10:609

This error was fixed by adding ``sudo apt-get install libegl1`` in my ci script, is it expected?

Steps to Reproduce:
- download and execute minizinc 2.7.2 appimage on system without libEGL, e.g. in github ci.

Expected Behavior:
- Successful execution of minizinc python wrapper

Actual Behavior:
- `error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory`

**Comment by cyderize** [comment]
Hi, this is because we have upgraded the Linux packages to use Qt6 which now requires `libEGL`. This library is blacklisted by `linuxdeploy` because it is system/graphics driver specific.

Unfortunately CI environments often don't have this library because they are headless, so installing it with `apt-get install libegl1`  is the right fix I think.

In the next release we may investigate packaging libEGL manually and only using it if not present on the system, but I'm not sure if this would actually work.
