### ISSUE TITLE
"Model parameter" window shows closed files

### ISSUE THREAD

**Issue by cprudhom** [MiniZinc/MiniZincIDE#198]
After closing models and datasets, the "Model parameter" and "Select a model to run" windows still offer them as possible choices.
Sometimes only one model and its dataset are open, but you still have to choose from a list.
If you choose a model or dataset that is not open, it is considered to be active and no errors are raised.

Version 2.8.0, 1074266394
macOS 13.5.2 (22G91)

**Comment by cyderize** [comment]
I believe this is the expected behaviour - although I can see why it seems strange.

The IDE actually works with 'projects', so if you click the 'Show project explorer' button, you'll see that those data files are still in the project - closing tabs doesn't remove them from the project. Removing them using the project explorer will then remove them from the list of suggested files.
