### ISSUE TITLE
Flattening Error

### ISSUE THREAD

**Issue by Bluetaurean** [MiniZinc/MiniZincIDE#38]
When i run the below i get this error
"MiniZinc: flattening error: 
  Model does not have a solve item"

"var 100..800: army;

constraint army mod 5 = 2;
constraint army mod 7 = 2;
constraint army mod 12 = 1;

solve satisfy;"

**Comment by a1880** [comment]
The following results in 457 without problems:

```
var 100..800: army;
constraint (army mod 5) = 2;
constraint (army mod 7) = 2;
constraint (army mod 12) = 1;
solve satisfy;
```
It is probably a matter of operator precedence between "mod" and "=".

**Comment by Bluetaurean** [comment]
I just noticed that the original code runs when it is not saved as count.mzn;
all other file names seem to work but not count.mzn

**Comment by ppcaric** [comment]
I've just had the same issue with a model named knapsack.mzn
After seeing your issue report I understood that the problem is in the name, since a knapsack.mzn exists in the standard library minizinc uses and it conflicts with my own model, but without letting me know it!
I guess a good improvement in the IDE would be to prevent the user from giving a name to a model that is already used in the standard library...
