### ISSUE TITLE
Gurobi Solver: dll is missing in Windows

### ISSUE THREAD

**Issue by zarmeen92** [MiniZinc/MiniZincIDE#45]
I tried to run model using Gurobi(bundled) solver in Minizinc IDE 2.1.6 but the following error occured

**MiniZinc: internal error: cannot load gurobi dll**
I understand that it might be due to the license issue. But I have now download gurobi optimizer licensed version. Any help on how to interface the gurobi optimizer in minizinc

**Comment by Dekker1** [comment]
This is indeed an issue due to licensing. We don't actually bundle the Gurobi solver with the MiniZinc bundle, just a wrapper for MiniZinc to interact with the Gurobi solver already installed on your system.

The problem you're experiencing is that we need to know what version of Gurobi to load. Even though the versions are compatible, the version and its name are necessary to load the actual solver. The `mzn-gurobi` executable in MiniZinc `2.1.6` looks for versions `6.5` or `7.0`. If either of these versions is installed on your system, the DLL should automatically be found.

In future versions of the MiniZinc bundle an extra flag has been added to `mzn-gurobi`, `--dll`, which will allow you to select the version of gurobi that you have installed on your system.

**Comment by zarmeen92** [comment]
thanks @Dekker1. I installed version 7.0 of Gurobi and its working now.
