### ISSUE TITLE
IDE editor configuration

### ISSUE THREAD

**Issue by pierfle** [MiniZinc/MiniZincIDE#65]
Did I miss something about configuring the IDE editor, else this is a wish list:
+ Display column number of cursor [I think this used to be a feature, but I cannot find it now];
+ Enable more Emacs commands, especially for word/line deletions, such as Ctrl-k.

**Comment by guidotack** [comment]
The column number display will be part of the next release. I'm reluctant to add Emacs shortcuts (others would prefer vi...), since the editor module supports the platform specific standard shortcuts (e.g. Alt+cursor for moving/deleting per word, Cmd+cursor for moving to beginning/end of line on macOS).
