### ISSUE TITLE
MiniZinc's output command in Jupyter/Linux

### ISSUE THREAD

**Issue by ido97** [MiniZinc/MiniZincIDE#72]
The output command in MiniZinc under Jupyter/Linux is not executing.

When running:

    %%minizinc 
    var int: one_var;
    constraint one_var = 1;
    solve satisfy;
    output ["my var = \(2*one_var)\n"];

I'm getting
{'one_var': 1} which is the standard MiniZinc variables' output,

instead of
my var = 2

Thank Ido

**Comment by Dekker1** [comment]
Hi Ido,

I'm afraid that this is expected behaviour. When using the IPython interface to MiniZinc, the MiniZinc variables are communicated directly back to Python and the output item is ignored. This is similar to setting the output modes for MiniZinc on the command-line. You can use python to format the variables in any way you like. If you want to do mathematical transformations on the variables you can even add them to the model:
```
var int: my_var = 2*one_var;
```

One thing that could be interesting is to add a feature to the python package to print the formatted output statement. Note that this would only add output to the screen and the print statement output would not be able to be used further on other than as a string.

Feel free to open a feature request for this feature in the corresponding repository: https://github.com/MiniZinc/iminizinc. I'll close this issue as it is not relevant to the MiniZincIDE

**Comment by ido97** [comment]
Hi Jip,
Thanks,
Ido
