### ISSUE TITLE
Compilation option -I and -G on same directory produce different output

### ISSUE THREAD

**Issue by jacopoMauro** [MiniZinc/MiniZincIDE#91]
I compile the example zebra.mzn (https://github.com/CP-Unibo/sunny-cp/blob/master/test/examples/zebra.mzn) with chuffed global redefinitions and the result varies if I use the -G option or the -I option passing the same directory.

minizinc --compile --fzn /z1.fzn -I /tool/MiniZincIDE/share/minizinc/chuffed/ /tool/sunny-cp/test/examples/zebra.mzn && \
minizinc --compile --fzn /z2.fzn -Gchuffed /tool/sunny-cp/test/examples/zebra.mzn && \
diff /z1.fzn /z2.fzn

The diff outputs the following

2d1
< predicate int_lin_eq_imp(array [int] of int: as,array [int] of var int: bs,int: c,var bool: r);
39,44c38,43
< constraint int_lin_eq_imp(X_INTRODUCED_27_,[X_INTRODUCED_11_,X_INTRODUCED_22_],1,X_INTRODUCED_29_):: defines_var(X_INTRODUCED_29_);
< constraint int_lin_eq_imp(X_INTRODUCED_27_,[X_INTRODUCED_22_,X_INTRODUCED_11_],1,X_INTRODUCED_31_):: defines_var(X_INTRODUCED_31_);
< constraint int_lin_eq_imp(X_INTRODUCED_27_,[X_INTRODUCED_12_,X_INTRODUCED_8_],1,X_INTRODUCED_33_):: defines_var(X_INTRODUCED_33_);
< constraint int_lin_eq_imp(X_INTRODUCED_27_,[X_INTRODUCED_8_,X_INTRODUCED_12_],1,X_INTRODUCED_35_):: defines_var(X_INTRODUCED_35_);
< constraint int_lin_eq_imp([1],[X_INTRODUCED_9_],2,X_INTRODUCED_37_):: defines_var(X_INTRODUCED_37_);
< constraint int_lin_eq_imp([-1],[X_INTRODUCED_9_],0,X_INTRODUCED_39_):: defines_var(X_INTRODUCED_39_);
---
> constraint int_lin_eq_reif(X_INTRODUCED_27_,[X_INTRODUCED_11_,X_INTRODUCED_22_],1,X_INTRODUCED_29_):: defines_var(X_INTRODUCED_29_);
> constraint int_lin_eq_reif(X_INTRODUCED_27_,[X_INTRODUCED_22_,X_INTRODUCED_11_],1,X_INTRODUCED_31_):: defines_var(X_INTRODUCED_31_);
> constraint int_lin_eq_reif(X_INTRODUCED_27_,[X_INTRODUCED_12_,X_INTRODUCED_8_],1,X_INTRODUCED_33_):: defines_var(X_INTRODUCED_33_);
> constraint int_lin_eq_reif(X_INTRODUCED_27_,[X_INTRODUCED_8_,X_INTRODUCED_12_],1,X_INTRODUCED_35_):: defines_var(X_INTRODUCED_35_);
> constraint int_lin_eq_reif([1],[X_INTRODUCED_9_],2,X_INTRODUCED_37_):: defines_var(X_INTRODUCED_37_);
> constraint int_lin_eq_reif([-1],[X_INTRODUCED_9_],0,X_INTRODUCED_39_):: defines_var(X_INTRODUCED_39_)

Is this a bug? From my understanding, the two options should output the same.

**Comment by Dekker1** [comment]
Hi @jacopoMauro,

Thank you for your patience. I'm sorry I haven't responded to your e-mail yet.

The difference in these two cases is caused by the solver setting. In the distributed version of the MiniZinc bundle, we ship a `Preferences.json` file which sets Gecode to be the default solver. This means that whenever no solver is specified, the MiniZinc driver will assume that you will use Gecode as the solver. (This allows us to do things like `minizinc model.mzn data.dzn` instead of `minizinc --solver gecode model.mzn data.dzn`).

In your case this means that when you used the `-G` flag, you replaced the globals library, which was set as `-Ggecode`, with the one for chuffed; however, when using the `-I` flag you only append the chuffed globals library to the existing gecode settings. Because gecode has a rather complete library, it is unlikely that any of the chuffed definitions where used.

To solve this problem you have a few options:
1. You can use the actual solver configurations and compile for chuffed with the solver flag: `minizinc --solver chuffed --compile --fzn z1.fzn zebra.mzn`
2. You can use recreate the behaviour of the old `mzn2fzn` executable by using the *base* solver configuration: `minizinc --solver org.minizinc.mzn-fzn  --fzn z1.fzn --compile -I ../share/minizinc/chuffed/ zebra.mzn`
3. You can change the default solver in the `.../share/minizinc/Preferences.json` file to be the *base* solver configuration:
```
{
	"tagDefaults": [
		["", "org.minizinc.mzn-fzn"]
	]
}
```

The first option would be the preferred solution as solver configurations will likely allow for more options in the future.
