### ISSUE TITLE
Error: Gecode: Float::linear: Number out of limits

### ISSUE THREAD

**Issue by markwallacemonash** [MiniZinc/MiniZincIDE#94]
I change
var float: SV = 0.2 ;
to
var 0.2..0.2:SV ;
and the attached model gives the error:
Error: Gecode: Float::linear: Number out of limits
[black_scholes_2 - Copy.txt](https://github.com/MiniZinc/MiniZincIDE/files/3750159/black_scholes_2.-.Copy.txt)

**Comment by Dekker1** [comment]
In MiniZinc version 2.3.2. I'm getting a different error:
`Error: Registry: Constraint float_lin_ne not found`

The difference between the two versions is that MiniZinc knows at compile-time that SV is fixed in the first case, but in the second case keeps it as a variable. Because the expression `(SV * SV)/2.0` is used in the model, MiniZinc then forces `SV*SV` to not be zero by adding `0.7071067811865476 * SV != 0`. This issue could be resolved two ways:
- When a floating point domain is fixed, the compiler should take not of this.
- The compiler should be able to detect that the domain of `SV * SV` does not contain `0.0` and thus avoid adding the `!=` constraint.

Preferably we should do both as both problems can trigger separately.

**Comment by hectorpal** [comment]
Hi, I'm getting a similar error.
This was tested with the current bundle, 2.4.3 in Mac.
I tried and have the same error using the built-in Gecode and some others, including 6.1.1 and 6.2. 

It works if I use MiniZinc to FlatZinc converter, version 2.3.1 instead of 2.4.3.

The attached file also has a rewriting of the offending line.

[error-mzn-2020-07-07.dzn.txt](https://github.com/MiniZinc/MiniZincIDE/files/4885980/error-mzn-2020-07-07.dzn.txt)
[error-mzn-2020-07-07.mzn.txt](https://github.com/MiniZinc/MiniZincIDE/files/4885981/error-mzn-2020-07-07.mzn.txt)

**Comment by hectorpal** [comment]
So, this seems to be an issue in the mzn2fzn.

This bug spans a couple of minor versions now:
@markwallacemonash reported this on Oct 2019, but didn't mention the version, but it should have been < 2.40 as that was released later than that.

**Comment by hectorpal** [comment]
Let me know if I can help to narrow this down.
